
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'mts'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'my_profile'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In dbt, the default materialization for a model is a view. This means, when you run 
# dbt run or dbt build, all of your models will be built as a view in your data platform. 
# The configuration below will override this setting for models in the example folder to 
# instead be materialized as tables. Any models you add to the root of the models folder will 
# continue to be built as views. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.



vars:
  bronze_database: "{{ env_var('DBT_BRONZE_DATABASE') }}"
  bronze_schema: "{{ env_var('DBT_BRONZE_SCHEMA') }}"
  silver_database: "{{ env_var('DBT_SILVER_DATABASE') }}"
  silver_schema: "{{ env_var('DBT_SILVER_SCHEMA') }}"
  gold_database: "{{ env_var('DBT_GOLD_DATABASE') }}"
  gold_schema: "{{ env_var('DBT_GOLD_SCHEMA') }}"

models:
  mts:
    # Bronze layer - raw data from source systems
    bronze:
      +materialized: table  
      +schema: "{{ env_var('DBT_BRONZE_SCHEMA') }}"
      +database: "{{ env_var('DBT_BRONZE_DATABASE') }}"
      +tags: ["bronze", "raw"]
    
    # Silver layer - cleaned and transformed data
    silver:
      +materialized: incremental
      +schema: "{{ env_var('DBT_SILVER_SCHEMA') }}"
      +database: "{{ env_var('DBT_SILVER_DATABASE') }}"
      +tags: ["silver", "transformed"]
    
    # Gold layer - business-ready aggregated data
    gold:
      +materialized: view
      +schema: "{{ env_var('DBT_GOLD_SCHEMA') }}"
      +database: "{{ env_var('DBT_GOLD_DATABASE') }}"     
      +tags: ["gold", "business"]

    
