version: 2

sources:
  - name: silver_data                # will become source('raw_data', ...)
    database: RAW_DATA            # your Snowflake database
    schema: SILVER_SALES          # your Snowflake schema
    tables:
      - name: DIM_SASLRM_FULL