-- Step 1: Load source data with all necessary fields
 WITH source_data AS (   SELECT
        -- Key fields
        CAST(TRIM(W1STORE) AS NUMBER(3, 0)) AS STORE_NUMBER,
        TRIM(W1FMTP) AS FORM_TYPE_CODE,
        TRIM(W1WIPX) AS POS_PREFIX,
        CAST(TRIM(W1WO) AS NUMBER(10, 0)) AS WORK_ORDER_NUMBER,
        
        -- Date fields
        TRIM(W1TRDT) AS TRANSACTION_DATE,
       TRIM(W1OTDT) AS ORIGIN_TRANSACTION_DATE,
        TRY_TO_DATE(TRIM(W1PRDT), 'YYYYMMDD') AS PRINT_DT,
        
        -- Dimension references
               
        CAST(TRIM(W1SRST) AS NUMBER(3, 0)) AS SALES_REP_STORE_NUMBER,
        CAST(TRIM(W1SLRP) AS NUMBER(10, 0)) AS SALES_REP_NUMBER,
        CAST(TRIM(W1CST) AS NUMBER(10, 0)) AS CUSTOMER_NUMBER,
        CAST(TRIM(W1NAVD) AS NUMBER(10, 0)) AS NATIONAL_ACCOUNT_VENDOR_NUMBER,
        TRIM(W1VSTS) AS VEHICLE_STATUS,
        CAST(TRIM(W1SHPN) AS NUMBER(10, 0)) AS SHIPPING_TO_NUMBER,
        
        -- Customer information
        TRIM(W1NAME) AS CUSTOMER_NAME,
        TRIM(W1ADR1) AS ADDRESS_LINE_1,
        TRIM(W1ADR2) AS ADDRESS_LINE_2,
        TRIM(W1ADR3) AS ADDRESS_LINE_3,
        TRIM(W1CITY) AS CITY,
        TRIM(W1STAT) AS STATE,
        TRIM(W1ZIP) AS ZIP_CODE,
        TRIM(W1WPHN) AS WORK_PHONE,
        TRIM(W1WPE1) AS WORK_PHONE_EXT,
        TRIM(W1HPHN) AS HOME_PHONE,
        CAST(TRIM(W1TMCD) AS NUMBER(3, 0)) AS TERMS_CODE,
        CAST(TRIM(W1TXCD) AS NUMBER(3, 0)) AS TAX_CODE,
        CAST(TRIM(W1TDCD) AS NUMBER(10, 0)) AS TAX_DISTRICT_CODE,
        CAST(TRIM(W1BLCD) AS NUMBER(3, 0)) AS BILLING_CODE,
        TRIM(W1DRNO) AS DRIVER_NUMBER,
        TRIM(W1PO) AS PURCHASE_ORDER_NUMBER,
        
        -- Shipping information
        TRIM(W1SHNM) AS SHIPPING_NAME,
        TRIM(W1SAD1) AS SHIP_ADDRESS_1,
        TRIM(W1SAD2) AS SHIP_ADDRESS_2,
        TRIM(W1SAD3) AS SHIP_ADDRESS_3,
        TRIM(W1SCTY) AS SHIP_CITY,
        TRIM(W1SSTa) AS SHIP_STATE,
        TRIM(W1SZIP) AS SHIP_ZIP,
        
        -- Origin information
        TRIM(W1OFMT) AS ORIGIN_FORM_TYPE_CODE,
        CAST(TRIM(W1OSRS) AS NUMBER(20, 0)) AS ORIGIN_SALES_REP_STORE_NUMBER,
        CAST(TRIM(W1OSLR) AS NUMBER(20, 0)) AS ORIGIN_SALES_REP_NUMBER,
        TRIM(W1STS) AS WORK_ORDER_STATUS,
        
        -- Flag fields
        TRIM(W1HOLD) AS HOLD_FLAG,
        TRIM(W1QSTS) AS QUESTION_ASKED_FLAG,
        TRIM(W1CSTS) AS COMMENT_FLAG,
        TRIM(W1AR) AS ACCT_REVERSAL_FLAG,
        TRIM(W1PYMT) AS PAYMENT_FLAG,
        TRIM(W1PYNM) AS PAYMENT_TYPE_NAME,
        
        -- Fact fields (measures)
        CAST(TRIM(W1TEXM) AS NUMERIC(12,2)) AS TOTAL_TAX_EXEMPT_AMT,
        CAST(TRIM(W1TTXB) AS NUMERIC(12,2)) AS TOTAL_TAXABLE_AMT,
        CAST(TRIM(W1TSLT) AS NUMERIC(12,2)) AS SALES_SALES_TAX_AMT,
        CAST(TRIM(W1TAMT) AS NUMERIC(12,2)) AS TOTAL_AMOUNT,
        CAST(TRIM(W1AMT) AS NUMERIC(12,2)) AS TOTAL_EXTENDED_AMT,
        CAST(TRIM(W1CAMT) AS NUMERIC(12,2)) AS TOTAL_EXTENDED_COST_AMT,
        CAST(TRIM(W1AMTGP) AS NUMERIC(12,2)) AS TOTAL_EXTENDED_GP_AMT,
        CAST(TRIM(W1CAMTGP) AS NUMERIC(12,2)) AS TOTAL_EXTENDED_COST_GP_AMT,
        CAST(TRIM(W1GPAM) AS NUMERIC(12,2)) AS TOTAL_GP_AMT,
        CAST(TRIM(W1GPMG) AS NUMERIC(9,6)) AS TOTAL_PROFIT_MARGIN,
        
        CAST(TRIM(W1GPNM) AS NUMERIC(12,2)) AS TOTAL_GP_NAB_AMT,
        
        CAST(TRIM(W1GPNG) AS NUMERIC(9,6)) AS TOTAL_NAB_PROFIT_MARGIN,
        
        CAST(TRIM(W1TSAM) AS NUMERIC(12,2)) AS TOTAL_SPIFF_AMT,
        CAST(TRIM(W1TSPT) AS NUMBER(3, 0)) AS TOTAL_SPIFF_POINTS,
        CAST(TRIM(W1TFEE) AS NUMERIC(12,2)) AS TOTAL_TIRE_FEE,
        CAST(TRIM(W1PRSQ) AS NUMBER(10, 0)) AS NUMBER_OF_TIMES_PRINTED,
        CAST(TRIM(W1NACD) AS NUMBER(9,2)) AS NAB_CREDIT_DUE,
        CAST(TRIM(W1NACR) AS NUMERIC(9,2)) AS NAB_CREDIT_RECEIVED,
        CAST(TRIM(W1NACP) AS NUMBER(9,2))   AS NAB_CREDIT_PENDING,
        
        -- Additional dimension fields
        CAST(TRIM(W1ARST) AS NUMERIC(20, 0)) AS CREDITED_SALES_REP_STORE_NUMBER,
        CAST(TRIM(W1ARRP) AS NUMERIC(20, 0)) AS CREDITED_SALES_REP_NUMBER,
        CAST(TRIM(W1STOREO) AS NUMERIC(20, 0)) AS ORIGIN_INVOICED_STORE_NUMBER,
        TRIM(W1FMTPO) AS ORIGIN_INVOICED_FORM_TYPE_CODE,
        TRIM(W1WIPXO) AS ORIGIN_INVOICED_POS_PREFIX,
        CAST(TRIM(W1WOO) AS NUMERIC(10, 0)) AS ORIGIN_INVOICED_WORK_ORDER_NUMBER,
        TRIM(W1CPAT) AS CORP_AUTH_ASKED_FLAG,
        
        
        
        
        -- Audit columns
        CAST(TRIM(SOURCE_SYSTEM) AS VARCHAR(100)) AS SOURCE_SYSTEM,
        CAST(TRIM(SOURCE_FILE_NAME) AS VARCHAR(255)) AS SOURCE_FILE_NAME,
        CAST(TRIM(BATCH_ID) AS VARCHAR(100)) AS BATCH_ID,
        CAST(TRIM(ETL_VERSION) AS VARCHAR(50)) AS ETL_VERSION,
        CAST(TRIM(OPERATION) AS VARCHAR(10)) AS OPERATION,
        MD5(CONCAT_WS('|',
    TRIM(W1TRDT),
    TRIM(W1OTDT),
    TRIM(W1PRDT),
    TRIM(W1SRST),
    TRIM(W1SLRP),
    TRIM(W1CST),
    TRIM(W1NAVD),
    TRIM(W1VSTS), -- VEHICLE_STATUS is same as W1NAVD
    TRIM(W1SHPN),
    TRIM(W1NAME),
    TRIM(W1ADR1),
    TRIM(W1ADR2),
    TRIM(W1ADR3),
    TRIM(W1CITY),
    TRIM(W1STAT),
    TRIM(W1ZIP),
    TRIM(W1WPHN),
    TRIM(W1WPE1),
    TRIM(W1HPHN),
    TRIM(W1TMCD),
    TRIM(W1TXCD),
    TRIM(W1TDCD),
    TRIM(W1BLCD),
    TRIM(W1DRNO),
    TRIM(W1PO),
    TRIM(W1SHNM),
    TRIM(W1SAD1),
    TRIM(W1SAD2),
    TRIM(W1SAD3),
    TRIM(W1SCTY),
    TRIM(W1SSTa),
    TRIM(W1SZIP),
    TRIM(W1OFMT),
    TRIM(W1OSRS),
    TRIM(W1OSLR),
    TRIM(W1STS),
    TRIM(W1HOLD),
    TRIM(W1QSTS),
    TRIM(W1CSTS),
    TRIM(W1AR),
    TRIM(W1PYMT),
    TRIM(W1PYNM),
    TRIM(W1TEXM),
    TRIM(W1TTXB),
    TRIM(W1TSLT),
    TRIM(W1TAMT),
    TRIM(W1AMT),
    TRIM(W1CAMT),
    TRIM(W1AMTGP),
    TRIM(W1CAMTGP),
    TRIM(W1GPAM),
    TRIM(W1GPMG),
    TRIM(W1GPNM),
    TRIM(W1GPNG),
    TRIM(W1TSAM),
    TRIM(W1TSPT),
    TRIM(W1TFEE),
    TRIM(W1PRSQ),
    TRIM(W1NACD),
    TRIM(W1NACR),
    TRIM(W1NACP),
    TRIM(W1ARST),
    TRIM(W1ARRP),
    TRIM(W1STOREO),
    TRIM(W1FMTPO),
    TRIM(W1WIPXO),
    TRIM(W1WOO),
    TRIM(W1CPAT)
)) AS  RECORD_CHECKSUM_HASH,
        
        -- Create a tracking hash for change detection
            TO_TIMESTAMP_NTZ(TRIM(ENTRY_TIMESTAMP)) AS ENTRY_TIMESTAMP
        FROM {{ source('bronze_data', 'T_BRZ_HEADER_WOMSTH') }}
    {% if is_incremental() %}

    WHERE ENTRY_TIMESTAMP ='1900-01-01T00:00:00Z'

    {% endif %}
),

-- Step 2: Join with dimension tables to get surrogate keys

    SELECT
        sd.*,
        dt.DIM_DATE_KEY AS TRANSACTION_DATE_SK,
        odt.DIM_DATE_KEY AS ORIGIN_TRANSACTION_SK,
        srst.STORE_SK AS SALES_REP_STORE_SK,
        sr.SALES_REP_SK,
        c.CUSTOMER_SK,
        -- Additional surrogate keys for form types
        ft.FORM_TYPE_SK AS ORIGIN_FORM_TYPE_SK,
        ift.FORM_TYPE_SK AS ORIGIN_INVOICED_FORM_TYPE_SK,
        -- Additional surrogate keys for stores
        orst.STORE_SK AS ORIGIN_SALES_REP_STORE_SK,
        crst.STORE_SK AS CREDITED_SALES_REP_STORE_SK,
        ist.STORE_SK AS ORIGIN_INVOICED_STORE_SK,
        -- Additional surrogate keys for sales reps
        orsr.SALES_REP_SK AS ORIGIN_SALES_REP_SK,
        crsr.SALES_REP_SK AS CREDITED_SALES_REP_SK
    FROM source_data sd
    -- Date dimension lookups
    LEFT JOIN {{ source('silver_data', 'T_DIM_DATE') }} dt  ON dt.DATE_KEY = sd.TRANSACTION_DATE 
    LEFT JOIN {{ source('silver_data', 'T_DIM_DATE') }} odt ON odt.DATE_KEY = sd.ORIGIN_TRANSACTION_DATE
    
    -- Store dimension lookups
    LEFT JOIN {{ ref('T_DIM_STORE') }} srst ON srst.STORE_NUMBER = sd.SALES_REP_STORE_NUMBER AND srst.IS_CURRENT_FLAG = TRUE
    LEFT JOIN {{ ref('T_DIM_STORE') }} orst ON orst.STORE_NUMBER = sd.ORIGIN_SALES_REP_STORE_NUMBER AND orst.IS_CURRENT_FLAG = TRUE
    LEFT JOIN {{ ref('T_DIM_STORE') }} crst ON crst.STORE_NUMBER = sd.CREDITED_SALES_REP_STORE_NUMBER AND crst.IS_CURRENT_FLAG = TRUE
    LEFT JOIN {{ ref('T_DIM_STORE') }} ist ON ist.STORE_NUMBER = sd.ORIGIN_INVOICED_STORE_NUMBER AND ist.IS_CURRENT_FLAG = TRUE
    
    -- Sales rep dimension lookups
    LEFT JOIN {{ ref('T_DIM_SALES_REP') }} sr ON sr.SALES_REP_NUMBER = sd.SALES_REP_NUMBER AND sr.IS_CURRENT_FLAG = TRUE
    LEFT JOIN {{ ref('T_DIM_SALES_REP') }} orsr  ON orsr.SALES_REP_NUMBER = sd.ORIGIN_SALES_REP_NUMBER AND orsr.IS_CURRENT_FLAG = TRUE
    LEFT JOIN {{ ref('T_DIM_SALES_REP') }} crsr crsr ON crsr.SALES_REP_NUMBER = sd.CREDITED_SALES_REP_NUMBER AND crsr.IS_CURRENT_FLAG = TRUE
    
    -- Form type dimension lookups
    LEFT JOIN {{ ref('T_DIM_FORM_TYPE') }} ft ON ft.FORM_TYPE_CODE = sd.ORIGIN_FORM_TYPE_CODE AND ft.IS_CURRENT_FLAG = TRUE
    LEFT JOIN {{ ref('T_DIM_FORM_TYPE') }} ift ON ift.FORM_TYPE_CODE = sd.ORIGIN_INVOICED_FORM_TYPE_CODE AND ift.IS_CURRENT_FLAG =TRUE
    
    -- Customer dimension lookup
    LEFT JOIN {{ ref('T_DIM_CUSTOMER') }} c ON c.CUSTOMER_ID = sd.CUSTOMER_NUMBER AND c.IS_CURRENT_FLAG = TRUE
