select CAST(TRIM(M3STORE) AS NUMBER(3, 0)) AS STORE_NUMBER,
        CAST(TRIM(M3NAME) AS VARCHAR(40)) AS MANAGER_NAME,
        CAST(TRIM("M3CELL#") AS VARCHAR(10)) AS CELL_NUMBER,
        CAST(TRIM(M3EMAIL) AS VARCHAR(60)) AS EMAIL_ADDRESS,
        CAST(TRIM(M3SLRP) AS NUMBER(5, 0)) AS BASYS_SALESREP_NUMBER,
        CAST(TRIM(M3RSM) AS NUMBER(5, 0)) AS REGIONAL_SALES_MANAGER_NUMBER,
        CAST(TRIM(M3ROM) AS NUMBER(5, 0)) AS REGIONAL_OPERATIONS_MANAGER_NUMBER,
        CAST(TRIM(M3ADM) AS NUMBER(5, 0)) AS AREA_DIRECTOR_MANAGER_NUMBER,
        CAST(TRIM(M3PAY) AS NUMBER(5, 0)) AS PAYROLL_SALESREP_NUMBER,
        CAST(TRIM(M3MGR) AS NUMBER(5, 0)) AS STORE_MANAGER_SALESREP_NUMBER,
        CAST(TRIM(M3MFGROM) AS NUMBER(5, 0)) AS MFG_REGIONAL_OPERATIONS_MANAGER_NUMBER,
        CAST(TRIM(SOURCE_SYSTEM) AS VARCHAR(100)) AS SOURCE_SYSTEM,
        CAST(TRIM(SOURCE_FILE_NAME) AS VARCHAR(255)) AS SOURCE_FILE_NAME,
        CAST(TRIM(BATCH_ID) AS VARCHAR(100)) AS BATCH_ID,
        CAST(TRIM(ETL_VERSION) AS VARCHAR(50)) AS ETL_VERSION,

        MD5(CONCAT_WS('|',
            COALESCE(TRIM(M3NAME), ''),
            COALESCE(TRIM("M3CELL#"), ''),
            COALESCE(TRIM(M3EMAIL), ''),
            COALESCE(TRIM(M3SLRP), ''),
            COALESCE(TRIM(M3RSM), ''),
            COALESCE(TRIM(M3ROM), ''),
            COALESCE(TRIM(M3ADM), ''),
            COALESCE(TRIM(M3PAY), ''),
            COALESCE(TRIM(M3MGR), ''),
            COALESCE(TRIM(M3MFGROM), '')
        )) AS RECORD_CHECKSUM_HASH,

        TO_TIMESTAMP_NTZ(TRIM(ENTRY_TIMESTAMP)) AS ENTRY_TIMESTAMP

    FROM {{ source('bronze_data', 'T_BRZ_STOREMANAGER_STMGRS') }}