version: 2

sources:
  - name: bronze_data                # will become source('raw_data', ...)
    database: RAW_DATA            # your Snowflake database
    schema: BRONZE_SALES          # your Snowflake schema
    tables:
      - name: T_BRZ_SALESREP_MASTER_SASLRM
      - name: T_BRZ_STORE_MASTER_STMAST    
      - name: T_BRZ_STOREMANAGER_STMGRS
      - name: T_BRZ_FORMTYPE_WOFMTP
      - name: T_BRZ_INV_CAT_INCATG
      - name: T_BRZ_CUSTOMER_MASTER_SACUST
      - name: T_BRZ_TIRE_MASTER_ITCLVT