version: 2

sources:
  - name: raw_data                # will become source('raw_data', ...)
    database: RAW_DATA            # your Snowflake database
    schema: ANALYTICS          # your Snowflake schema
    tables:
      - name: T_BRZ_SALESREP_MASTER_SASLR_CLONED