SELECT
    ENTRY_TIMESTAMP,
    SEQUENCE_NUMBER,
    OPERATION,
    M0SLRP,
    M0NAME,
    M0SPCM,
    SOURCE_SYSTEM,
    SOURCE_FILE_NAME,
    BATCH_ID,
    RECORD_CHECKSUM_HASH,
    ETL_VERSION,
    INGESTION_DTTM,
    INGESTION_DT
FROM BRONZE_SALES.T_BRZ_SALESREP_MASTER_SASLRM